apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-iyyh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-iyyh
    app.kubernetes.io/part-of: netlifytrial-2
  name: netlifytrial-iyyh
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: netlifytrial-iyyh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: netlifytrial-iyyh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/netlifytrial-2/netlifytrial-iyyh@sha256:993e311c112199fa62eda4e753292d2d515752dc1933adb6c5fd97e925e6dc5c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
