apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-olvm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-olvm
    app.kubernetes.io/part-of: netlifytrial-2
  name: netlifytrial-olvm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: netlifytrial-olvm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: netlifytrial-olvm
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/netlifytrial-2/netlifytrial-olvm@sha256:01ba25895a60b95ad1ff2198459c6724c2f82ebb13e21d0e3670a85eba0504cd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
